version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb+srv://janithniroshan961:m1DXsoNBWrxKwALP@cluster0.6xoem.mongodb.net/test
      - NEXTAUTH_SECRET=secret123
      - NEXTAUTH_URL=http://localhost:3000
      - ADMIN_USERNAME=vili
      - ADMIN_PASSWORD=123123
      - NEXT_PUBLIC_CLOUD_NAME=doojo83ea
      - NEXT_PUBLIC_UPLOAD_PRESET=travel_booking_app
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_51MtmNrADDJBvTXeE8k7dQAs8TpVeh4bUePte54NuhPpsDkSerUcyIqZxbV3KaDREEhDkNDV7Akx5o0jEgqbov4Yo007GYWYtgB
      - STRIPE_SECRET_KEY=sk_test_51MtmNrADDJBvTXeE48nulA4gmsMFtshXNDbuWqSwL48PLewF0Zrm9wRf6aYUDx4koRVsk81R2446wBfYmgUSjCS700cUzj0C6b
      - STRIPE_WEBHOOK_SECRET=whsec_2f084c46e6db08a1c1afc385fcdd4b1bae411093a3ed55f2c58fdcd77bafa24f
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    networks:
      - app-network
    restart: unless-stopped

  prisma-studio:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=mongodb+srv://janithniroshan961:m1DXsoNBWrxKwALP@cluster0.6xoem.mongodb.net/test
    command: npx prisma studio --hostname 0.0.0.0
    networks:
      - app-network
    depends_on:
      - client

networks:
  app-network:
    driver: bridge

volumes:
  app-data:
    driver: local