version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb+srv://janithniroshan961:m1DXsoNBWrxKwALP@cluster0.6xoem.mongodb.net/test
    depends_on:
      - backend

  backend:
    build:
      context: ./client
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb+srv://janithniroshan961:m1DXsoNBWrxKwALP@cluster0.6xoem.mongodb.net/test